/******************************************************************************
 * Copyright 2013, Qualcomm Innovation Center, Inc.
 *
 *    All rights reserved.
 *    This file is licensed under the 3-clause BSD license in the NOTICE.txt
 *    file for this project. A copy of the 3-clause BSD license is found at:
 *
 *        http://opensource.org/licenses/BSD-3-Clause.
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the license is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the license for the specific language governing permissions and
 *    limitations under the license.
 ******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler */

#ifndef _Included_org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler
#define _Included_org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_INITIALIZE
#define org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_INITIALIZE 0L
#undef org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_SHUTDOWN
#define org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_SHUTDOWN 10L
/*
 * Class:     org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_initialize
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_ioe_services_audiostreaming_player_jni_BusHandler_shutdown
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
